export default {
  blogTitle: 'LifeGadget',
  blogSubTitle: '生活をサポートする記事メディア',
  blogTitleTag: 'LifeGadget（ライフガジェット）',
  blogDomain: 'lifegadget.me',
  // blogUrl: 'http://localhost:8080/wordpress',
  blogUrl: 'http://localhost:8888',
  // blogUrl: 'http://wp.lifegadget.me',
  blogLogoImage: '/assets/image/lifegadget_white.png',
  blogDefaultImage: '/assets/image/lifegadget.png',
  perPage: 12,
  twitter: '@lifegadgetme',
  analyticsCode: 'UA-90112421-1',
  adsenseCode: 'ca-pub-5496880555378290',
};
